// AUTO-GENERATED by shared/codegen/gen-constants.mjs from shared/constants/colors.json — DO NOT EDIT.
// 値を変えるときは単一ソース (shared/constants/colors.json) を編集して `cd desktop && npm run codegen` を実行する。
import type { PresetColor } from './colors'

export const PRESET_COLORS: PresetColor[] = [
  { key: 'red-100', label: '赤', bg: 'bg-red-100 dark:bg-red-900/40', text: 'text-red-900 dark:text-red-100' },
  { key: 'orange-100', label: 'オレンジ', bg: 'bg-orange-100 dark:bg-orange-900/40', text: 'text-orange-900 dark:text-orange-100' },
  { key: 'yellow-100', label: '黄', bg: 'bg-yellow-100 dark:bg-yellow-900/40', text: 'text-yellow-900 dark:text-yellow-100' },
  { key: 'green-100', label: '緑', bg: 'bg-green-100 dark:bg-green-900/40', text: 'text-green-900 dark:text-green-100' },
  { key: 'teal-100', label: 'ティール', bg: 'bg-teal-100 dark:bg-teal-900/40', text: 'text-teal-900 dark:text-teal-100' },
  { key: 'blue-100', label: '青', bg: 'bg-blue-100 dark:bg-blue-900/40', text: 'text-blue-900 dark:text-blue-100' },
  { key: 'indigo-100', label: 'インディゴ', bg: 'bg-indigo-100 dark:bg-indigo-900/40', text: 'text-indigo-900 dark:text-indigo-100' },
  { key: 'purple-100', label: '紫', bg: 'bg-purple-100 dark:bg-purple-900/40', text: 'text-purple-900 dark:text-purple-100' },
  { key: 'pink-100', label: 'ピンク', bg: 'bg-pink-100 dark:bg-pink-900/40', text: 'text-pink-900 dark:text-pink-100' },
  { key: 'gray-100', label: 'グレー', bg: 'bg-neutral-100 dark:bg-neutral-700/40', text: 'text-neutral-900 dark:text-neutral-100' },
]
